module.exports = {
  DB_CREATION: `CREATE SCHEMA IF NOT EXISTS assignment2;`,
  TABLE_CREATION: `
  CREATE TABLE IF NOT EXISTS assignment2.users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NULL DEFAULT NULL,
    email VARCHAR(45) NULL DEFAULT NULL,
    password VARCHAR(45) NULL DEFAULT NULL,
    topic VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (id))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;
  `
};
